pipeline{
  agent any
  stages{
    stage("build image"){
      steps{
        sh "docker build -t library-management-api ./api/" 
        echo "image built successfully"
      }     
    }
    stage("push image to ACR"){
      steps{
        echo "pushing to ACR stage"
      }
    }
  }
}