pipeline{
  agent any
  environment{
    AZURE_REPO='myprivaterepo.azurecr.io'
  }
  stages{
    stage("build image"){
      steps{
        sh "docker build -t myprivaterepo.azurecr.io/library-management-api ./api/" 
        echo "image built successfully"
      }     
    }
    stage("push image to ACR"){
      steps{
        echo "pushing to ACR stage"
        withCredentials([usernamePassword(credentialsId: 'azure-credentials', passwordVariable: 'PASS', usernameVariable: 'USER')]){
          sh "echo $PASS | docker login ${AZURE_REPO} --username $USER --password-stdin"
          sh "nslookup myprivaterepo.azurecr.io"
          sh "docker push myprivaterepo.azurecr.io/library-management-api"
        }
        echo "image pushed successfully to azure container registry"
      }
    }
    stage("deploy image on kubernetes cluster"){
      steps{
        sh 'az account set --subscription cc7b3e92-7412-47e3-abe0-b6f5315d0d09'
        sh 'az aks get-credentials --resource-group k8s-rg --name k8s-cluster'
        sh "kubectl apply -f ./k8s/mysql-service.yaml"
        sh "kubectl apply -f ./k8s/app-deployment.yaml"
        sh "kubectl apply -f ./k8s/app-service.yaml"
      }
    }
  }
}